// Code generated by MockGen. DO NOT EDIT.
// Source: /home/alex/projects/ofm-microservices/ofm-api-gateway/internal/presentation/http/type.go
//
// Generated by this command:
//
//	mockgen -source=/home/alex/projects/ofm-microservices/ofm-api-gateway/internal/presentation/http/type.go -destination=/home/alex/projects/ofm-microservices/ofm-api-gateway/internal/presentation/http/mock_test.go -package=http
//

// Package http is a generated GoMock package.
package http

import (
	context "context"
	reflect "reflect"

	v2 "github.com/gofiber/fiber/v2"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthHandler is a mock of AuthHandler interface.
type MockAuthHandler struct {
	ctrl     *gomock.Controller
	recorder *MockAuthHandlerMockRecorder
	isgomock struct{}
}

// MockAuthHandlerMockRecorder is the mock recorder for MockAuthHandler.
type MockAuthHandlerMockRecorder struct {
	mock *MockAuthHandler
}

// NewMockAuthHandler creates a new mock instance.
func NewMockAuthHandler(ctrl *gomock.Controller) *MockAuthHandler {
	mock := &MockAuthHandler{ctrl: ctrl}
	mock.recorder = &MockAuthHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthHandler) EXPECT() *MockAuthHandlerMockRecorder {
	return m.recorder
}

// HandleSignUp mocks base method.
func (m *MockAuthHandler) HandleSignUp(c *v2.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleSignUp", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleSignUp indicates an expected call of HandleSignUp.
func (mr *MockAuthHandlerMockRecorder) HandleSignUp(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleSignUp", reflect.TypeOf((*MockAuthHandler)(nil).HandleSignUp), c)
}

// RegisterRoutes mocks base method.
func (m *MockAuthHandler) RegisterRoutes(router v2.Router) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterRoutes", router)
}

// RegisterRoutes indicates an expected call of RegisterRoutes.
func (mr *MockAuthHandlerMockRecorder) RegisterRoutes(router any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterRoutes", reflect.TypeOf((*MockAuthHandler)(nil).RegisterRoutes), router)
}

// MockServer is a mock of Server interface.
type MockServer struct {
	ctrl     *gomock.Controller
	recorder *MockServerMockRecorder
	isgomock struct{}
}

// MockServerMockRecorder is the mock recorder for MockServer.
type MockServerMockRecorder struct {
	mock *MockServer
}

// NewMockServer creates a new mock instance.
func NewMockServer(ctrl *gomock.Controller) *MockServer {
	mock := &MockServer{ctrl: ctrl}
	mock.recorder = &MockServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServer) EXPECT() *MockServerMockRecorder {
	return m.recorder
}

// App mocks base method.
func (m *MockServer) App() *v2.App {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "App")
	ret0, _ := ret[0].(*v2.App)
	return ret0
}

// App indicates an expected call of App.
func (mr *MockServerMockRecorder) App() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "App", reflect.TypeOf((*MockServer)(nil).App))
}

// Shutdown mocks base method.
func (m *MockServer) Shutdown(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockServerMockRecorder) Shutdown(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockServer)(nil).Shutdown), ctx)
}

// Start mocks base method.
func (m *MockServer) Start() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockServerMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockServer)(nil).Start))
}
