// Code generated by MockGen. DO NOT EDIT.
// Source: /home/alex/projects/ofm-microservices/ofm-api-gateway/internal/application/type.go
//
// Generated by this command:
//
//	mockgen -source=/home/alex/projects/ofm-microservices/ofm-api-gateway/internal/application/type.go -destination=/home/alex/projects/ofm-microservices/ofm-api-gateway/internal/presentation/http/registration_service_mock_test.go -package=http
//

// Package http is a generated GoMock package.
package http

import (
	gateway "api-gateway/internal/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRegistrationPublisher is a mock of RegistrationPublisher interface.
type MockRegistrationPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockRegistrationPublisherMockRecorder
	isgomock struct{}
}

// MockRegistrationPublisherMockRecorder is the mock recorder for MockRegistrationPublisher.
type MockRegistrationPublisherMockRecorder struct {
	mock *MockRegistrationPublisher
}

// NewMockRegistrationPublisher creates a new mock instance.
func NewMockRegistrationPublisher(ctrl *gomock.Controller) *MockRegistrationPublisher {
	mock := &MockRegistrationPublisher{ctrl: ctrl}
	mock.recorder = &MockRegistrationPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistrationPublisher) EXPECT() *MockRegistrationPublisherMockRecorder {
	return m.recorder
}

// StartRegistration mocks base method.
func (m *MockRegistrationPublisher) StartRegistration(ctx context.Context, req gateway.SignUpRequest) (*gateway.SignUpResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartRegistration", ctx, req)
	ret0, _ := ret[0].(*gateway.SignUpResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartRegistration indicates an expected call of StartRegistration.
func (mr *MockRegistrationPublisherMockRecorder) StartRegistration(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartRegistration", reflect.TypeOf((*MockRegistrationPublisher)(nil).StartRegistration), ctx, req)
}

// MockRegistrationService is a mock of RegistrationService interface.
type MockRegistrationService struct {
	ctrl     *gomock.Controller
	recorder *MockRegistrationServiceMockRecorder
	isgomock struct{}
}

// MockRegistrationServiceMockRecorder is the mock recorder for MockRegistrationService.
type MockRegistrationServiceMockRecorder struct {
	mock *MockRegistrationService
}

// NewMockRegistrationService creates a new mock instance.
func NewMockRegistrationService(ctrl *gomock.Controller) *MockRegistrationService {
	mock := &MockRegistrationService{ctrl: ctrl}
	mock.recorder = &MockRegistrationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistrationService) EXPECT() *MockRegistrationServiceMockRecorder {
	return m.recorder
}

// SignUp mocks base method.
func (m *MockRegistrationService) SignUp(ctx context.Context, req gateway.SignUpRequest) (*gateway.SignUpResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignUp", ctx, req)
	ret0, _ := ret[0].(*gateway.SignUpResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignUp indicates an expected call of SignUp.
func (mr *MockRegistrationServiceMockRecorder) SignUp(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignUp", reflect.TypeOf((*MockRegistrationService)(nil).SignUp), ctx, req)
}

// VerifyEmail mocks base method.
func (m *MockRegistrationService) VerifyEmail(ctx context.Context, req gateway.VerifyEmailRequest) (*gateway.VerifyEmailResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyEmail", ctx, req)
	ret0, _ := ret[0].(*gateway.VerifyEmailResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyEmail indicates an expected call of VerifyEmail.
func (mr *MockRegistrationServiceMockRecorder) VerifyEmail(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyEmail", reflect.TypeOf((*MockRegistrationService)(nil).VerifyEmail), ctx, req)
}

// CompleteRegistration mocks base method.
func (m *MockRegistrationService) CompleteRegistration(ctx context.Context, req gateway.CompleteRegistrationRequest) (*gateway.CompleteRegistrationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteRegistration", ctx, req)
	ret0, _ := ret[0].(*gateway.CompleteRegistrationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompleteRegistration indicates an expected call of CompleteRegistration.
func (mr *MockRegistrationServiceMockRecorder) CompleteRegistration(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteRegistration", reflect.TypeOf((*MockRegistrationService)(nil).CompleteRegistration), ctx, req)
}
